### PR TITLE
feat(Client): Allow sending data in DELETE requests

### PR DESCRIPTION
**Pull request by joseotoro**

### CODE REVIEW

**Comment by plusvic** [comment]
This breaks backward compatibility. Is it strictly necessary? Do we have some API that expects to receive a DELETE request with data in the body?

**Comment by joseotoro** [comment]
In order to delete items from collections we need it: https://developers.virustotal.com/reference/collectionsidrelationship-2

**Comment by joseotoro** [comment]
We can change it and just implement DeleteData separately so it doesn't break the Delete.

**Comment by joseotoro** [comment]
https://github.com/VirusTotal/vt-go/pull/23

**Pull request merged**
